name: Tests trigger with Allure reporting
on:
  workflow_dispatch:
    inputs:
      cucumber_tags:
        description: 'Cucumber tags'
        required: true
        default: '@regression'
  # schedule:
    # - cron: '0 6 * * *'  # Schedule daily at 6 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CUCUMBER_TAGS: ${{ github.event.inputs.cucumber_tags || '@regression' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean compile

      - name: Run Cucumber tests
        run: mvn test -D'cucumber.filter.tags'=${CUCUMBER_TAGS}
        continue-on-error: true

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
          
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
  
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
